SUBDIR += bar
# Not in SUBDIR: both have the same PORTNAME on purpose (see
# bulk-strict-deps-default-duplicate-pkgname.sh), which would make the
# bulk-strict-deps-default-all.sh "-a" test's EXPECTED_* lists depend on which
# one wins the race.  Only reachable by explicit origin (bulk -f file / command
# line).
#SUBDIR += dup-a
#SUBDIR += dup-b
SUBDIR += foo-dep-invalid-flavor
