PORTNAME=	dup
DISTVERSION=	20161010
PORTREVISION=	0
CATEGORIES=	misc
MASTER_SITES=	#
DISTFILES=	#

MAINTAINER=	bdrewery@FreeBSD.org
COMMENT=	Collides with misc/dup-a on PKGNAME, for STRICT_DEPS tests

LICENSE=	BSD2CLAUSE

USES=		metaport

NO_BUILD=	yes
NO_ARCH=	yes

do-install:
	@${DO_NADA}

.include <bsd.port.mk>
